spring.application.name=member

# Import .env file
spring.config.import=optional:file:.env[.properties]

# Server Settings
server.port=${MEMBER_PORT}

# Timezone Setting
spring.jackson.time-zone=Asia/Seoul