server:
    port: 8082

spring:
    application:
        name: account

    jackson:
        time-zone: Asia/Seoul

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${USER_NAME}
        password: ${PASSWORD}

