server:
  port: 8087

spring:
  application:
    name: account

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

  kafka:
    bootstrap-servers: awoofinance-kafka:9092

aes :
  secret_key : ${AES_KEY}

ssafy :
  finance :
    api_key : ${SSAFY_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

feign:
  client:
    config:
      member-service:
        url: ${member-service.url}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true