server:
  port: 8087

spring:
  application:
    name: account

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

aes :
  secret_key : ${AES_KEY}

ssafy :
  finance :
    api_key : ${SSAFY_API_KEY}

