plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.awoo'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

ext {
	set('springCloudVersion', "2024.0.0")
}

dependencyManagement {
	imports {
		// Spring Cloud Gateway 추가
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/release' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	//Mysql
	runtimeOnly 'com.mysql:mysql-connector-j'

	//Kafka
	implementation 'org.springframework.kafka:spring-kafka'
	testImplementation 'org.springframework.kafka:spring-kafka-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//Swagger 의존성
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'

	//JWT 의존성
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	//비밀번호 암호화
	implementation 'org.springframework.security:spring-security-crypto:5.7.1'

	//Security
	implementation 'org.springframework.boot:spring-boot-starter-security'

	//S3
	implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'

	//AES 암호화
	implementation 'javax.xml.bind:jaxb-api:2.3.1'

	//Web Request
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	//Feign Client
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	// Eureka Client 추가
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
}

tasks.named('test') {
	useJUnitPlatform()
}