plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id "org.sonarqube" version "3.5.0.2730"
}

group = 'com.awoo'
version = '0.0.1-SNAPSHOT'

bootJar.enabled = false // 빌드시 현재 모듈(multi-module)의 .jar를 생성하지 않습니다.

repositories {
    mavenCentral()
}

// SonarQube 공통 설정 추가
sonar {
    properties {
        property "sonar.projectName", "AwOO"
        property "sonar.projectKey", "AwOO-project"
        property "sonar.host.url", "http://43.201.97.59:9002"
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.java.source", "17"
    }
}

subprojects { // 모든 하위 모듈들에 이 설정을 적용합니다.
    group 'com.example'
    version '0.0.1-SNAPSHOT'
    sourceCompatibility = '17'

    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies { // 모든 하위 모듈에 추가 될 의존성 목록입니다.
        implementation 'org.springframework.boot:spring-boot-starter'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'

        //Swagger 의존성
        implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'

        //모니터링 의존성
        implementation 'org.springframework.boot:spring-boot-starter-actuator'
        implementation 'io.micrometer:micrometer-registry-prometheus'
    }

    test {
        useJUnitPlatform()
    }
}