server:
  port: 8085

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: pet-service
          uri: lb://pet
          predicates:
            - Path=/api/pets/**
        - id : member-service
          uri : lb://member
          predicates:
            - Path=/api/members/**
        - id: payment-service-charge
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/charges
          filters:
            - name: JwtAuthenticationFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/charges
          filters:
            - name: JwtAuthenticationFilter



      discovery:
        locator:
          enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret_key: nD/99zQMrX/fypNsi0J2IG+h46ePk0hddF3uCwRQITw=
  access_expiration: 86400000
  refresh_expiration: 604800000


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG