server:
  port: 8086
  servlet:
    context-path: /api

spring:
  application:
    name: PAYMENT-SERVICE
#
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: paymentService
#      auto-offset-reset: earliest
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  kafka:
    producer:
      bootstrap-servers: j12c209.p.ssafy.io:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: j12c209.p.ssafy.io:9092
      group-id: payment
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false  # 헤더 타입 정보 무시
        spring.json.value.default.type: com.awoo.payment.ui.listener.event.UsedProductSoldOutBySafeEvent
        spring.json.trusted.packages: "*"  # 신뢰할 패키지

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

sms:
  cool:
    sms-key : ${COOL_SMS_KEY}
    sms-scret-key : ${COOL_SMS_SECRET_KEY}
    phone-number : ${COOL_SMS_FROM_PHONE}

ssafy :
  finance :
    api_key : ${SSAFY_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true