plugins {
    id 'java'
    id 'org.springframework.boot' version'3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.awoo'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2024.0.1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Eureka Client
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // MYSQL
    runtimeOnly 'com.mysql:mysql-connector-j'

    // OpenFeign
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // commons-lang3 추가
    implementation 'org.apache.commons:commons-lang3'

    // AWS S3 의존성 추가
    implementation(platform("software.amazon.awssdk:bom:2.27.21"))
    implementation("software.amazon.awssdk:s3")

    // Query Dsl
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    // websocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

// 1. Q-Class를 생성할 디렉토리 경로 설정
def querydslSrcDir = "build/generated/sources/annotationProcessor/java/main"


//2. JavaCompile Task를 수행하는 경우 생성된 소스코드의 출력 디렉토리를 설정
tasks.withType(JavaCompile).configureEach {
    options.generatedSourceOutputDirectory = file(querydslSrcDir)
}

//3. 소스 코드로 인식할 디렉토리에 Q-Class 파일을 추가. Q-Class가 JAVA의 클래스 처럼 취급됨.
sourceSets {
    main.java.srcDir querydslSrcDir
}

//4. Clean Task를 수행하는 경우 지정한 디렉토리를 삭제하도록 설정.
clean {
    delete file(querydslSrcDir)
}

